# Generated by Django 5.2.17 on 2026-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="One or two plain-language sentences, shown on the homepage card.",
                        max_length=220,
                    ),
                ),
                (
                    "extended_description",
                    models.TextField(
                        help_text="What this practice area covers, in plain language."
                    ),
                ),
                (
                    "who_its_for",
                    models.TextField(
                        help_text="Who this practice area is a good fit for."
                    ),
                ),
                (
                    "next_steps",
                    models.TextField(
                        help_text="What happens after the first conversation."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Practice area",
                "verbose_name_plural": "Practice areas",
                "ordering": ["order", "name"],
            },
        ),
    ]
