# Generated by Django 5.2.17 on 2026-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice_areas", "0002_seed_practice_areas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("specialization", models.CharField(max_length=150)),
                ("years_experience", models.PositiveIntegerField()),
                (
                    "bio",
                    models.TextField(
                        help_text="One or two sentences — who they are, not a full CV."
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="lawyers/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "practice_areas",
                    models.ManyToManyField(
                        related_name="lawyers", to="practice_areas.practicearea"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
