# Generated by Django 5.2.17 on 2026-08-28 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_seed_lawyers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Staff login linked to this lawyer, for dashboard access.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lawyer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
