# Generated by Django 5.2.17 on 2026-08-29 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="That doesn't look like a valid phone number — numbers, spaces and + are fine (e.g. 07xx xxx xxx).",
                        regex="^[0-9+()\\-\\s]{7,20}$",
                    )
                ],
            ),
        ),
    ]
