# Generated by Django 5.2.17 on 2026-08-28 13:24

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_seed_demo_case"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="Max 15 MB. Allowed types: pdf, doc, docx, odt, rtf, txt, jpg, jpeg, png",
                upload_to="case_documents/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "odt",
                            "rtf",
                            "txt",
                            "jpg",
                            "jpeg",
                            "png",
                        ]
                    ),
                    dashboard.models.validate_document_size,
                ],
            ),
        ),
    ]
