# Generated by Django 5.2.17 on 2026-08-28 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice_areas", "0002_seed_practice_areas"),
        ("team", "0002_seed_lawyers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=120)),
                (
                    "client_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[0-9+()\\-\\s]{7,20}$",
                            )
                        ],
                    ),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="A short description of the client's situation.",
                        max_length=280,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lawyer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Left blank means the client asked for the next available lawyer.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="team.lawyer",
                    ),
                ),
                (
                    "practice_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="practice_areas.practicearea",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "confirmed"])),
                        fields=("lawyer", "start_time"),
                        name="unique_active_slot_per_lawyer",
                    )
                ],
            },
        ),
    ]
